[package]
name = "RustierChain"
version = "0.1.0"
authors = ["CanonNi <canonnizq@gmail.com>", "T.S. Stiffens <tsstiffens@gmail.com>"]
edition = "2021"

[dependencies]
ggez = "0.9.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
once_cell = "1.20.1"